export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCES = 'PRODUCT_LIST_SUCCES'
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCES = 'PRODUCT_DETAILS_SUCCES'
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'